[32m2024-04-23 14:03:18 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2bf47cf4-eb55-44d4-a61d-db7dd1efc3bb - 20896 - LOGS_CAPTURED - Started capturing logs in process (pid: 20896).
[32m2024-04-23 14:03:18 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2bf47cf4-eb55-44d4-a61d-db7dd1efc3bb - 20896 - vis_dataset - STEP_START - Started execution of step "vis_dataset".
[32m2024-04-23 14:03:18 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2bf47cf4-eb55-44d4-a61d-db7dd1efc3bb - vis_dataset - Loading file from: /Users/isaacanderson/Desktop/CSE314/MarchMadness/projectDag/tmprc4x5hfk/storage/ncaa_cleaned using PickledObjectFilesystemIOManager...
[32m2024-04-23 14:03:18 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2bf47cf4-eb55-44d4-a61d-db7dd1efc3bb - 20896 - vis_dataset - ASSET_OBSERVATION - DagsterEventType.ASSET_OBSERVATION for step vis_dataset
[32m2024-04-23 14:03:18 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2bf47cf4-eb55-44d4-a61d-db7dd1efc3bb - 20896 - vis_dataset - LOADED_INPUT - Loaded input "ncaa_cleaned" using input manager "io_manager"
[32m2024-04-23 14:03:18 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2bf47cf4-eb55-44d4-a61d-db7dd1efc3bb - 20896 - vis_dataset - STEP_INPUT - Got input "ncaa_cleaned" of type "DataFrame". Warning! Type check failed.
[32m2024-04-23 14:03:18 -0500[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 2bf47cf4-eb55-44d4-a61d-db7dd1efc3bb - 20896 - vis_dataset - STEP_FAILURE - Execution of step "vis_dataset" failed.

dagster._core.errors.DagsterTypeCheckDidNotPass: Type check failed for step input "ncaa_cleaned" - expected type "DataFrame". Description: Value of type <class 'NoneType'> failed type check for Dagster type DataFrame, expected value to be of Python type pandas.core.frame.DataFrame.

Stack Trace:
  File "/Users/isaacanderson/anaconda3/envs/boo/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_plan.py", line 282, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Users/isaacanderson/anaconda3/envs/boo/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 494, in core_dagster_event_sequence_for_step
    for evt in check.generator(
  File "/Users/isaacanderson/anaconda3/envs/boo/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 394, in _type_checked_event_sequence_for_input
    raise DagsterTypeCheckDidNotPass(
[0m
